### ISSUE TITLE
cannot run "import ipywidgets as widgets"

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#1]
When I import pyexplainer_pyexplainer, there is an error as shown below

![image](https://user-images.githubusercontent.com/29193812/111254366-7776b380-8647-11eb-9afd-03c6d946935a.png)

I tried using `pip install ipywidgets` and `conda install ipywidgets` but both methods cannot fix the issue.

Do you have any idea to solve this issue?

**Comment by MichaelFu1998-create** [comment]
Hello, did you manage to solve this problem?

**Comment by oathaha** [comment]
I just comment the code that uses the library because I don't use it in my experiment.

However, I think I may have problem with my conda environment and jupyter notebook, which I think I found solution.

**Comment by MichaelFu1998-create** [comment]
Thanks for the update!
