### ISSUE TITLE
Getting error while running tutorial.ipynb in the browser

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [awsm-research/PyExplainer#17]
Hello,
I was trying to run code from the tutorial.ipynb but while running it on the web, in the first step, I am getting the following error:
![image](https://user-images.githubusercontent.com/29624037/173997923-7837e642-9916-4392-b4f5-9b2ebf6df4b2.png)

Can you please help to solve this? is there a chance that with Binder build, it couldn't install dependencies?

**Comment by MichaelFu1998-create** [comment]
Hi Shraddha,
Are you getting this error from Blinder Notebook?

**Comment by ShraddhaDevaiya** [comment]
> Hi Shraddha, Are you getting this error from Blinder Notebook?

yes

**Comment by MichaelFu1998-create** [comment]
Hi Shraddha,
I just rebuilt the Binder image and it should work now.
Please let me know if having any further questions.

**Comment by ShraddhaDevaiya** [comment]
> Hi Shraddha, I just rebuilt the Binder image and it should work now. Please let me know if having any further questions.

yeah, it is working now, thanks:)
