### ISSUE TITLE
return local model

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#3]
I think it would be beneficial for user if local model of explain() function is included in returned dictionary.

The current code looks like this
```
rule_obj = {'synthetic_data': synthetic_instances,
                    'synthetic_predictions': synthetic_predictions,
                    'X_explain': X_explain,
                    'y_explain': y_explain,
                    'indep': self.indep,
                    'dep': self.dep,
                    'top_k_positive_rules': top_k_positive_rules,
                    'top_k_negative_rules': top_k_negative_rules}
```

but I think it should looks like this
```
rule_obj = {'synthetic_data': synthetic_instances,
                    'synthetic_predictions': synthetic_predictions,
                    'X_explain': X_explain,
                    'y_explain': y_explain,
                    'indep': self.indep,
                    'dep': self.dep,
                    'local_model': local_rulefit_model,
                    'top_k_positive_rules': top_k_positive_rules,
                    'top_k_negative_rules': top_k_negative_rules}
```

**Comment by MichaelFu1998-create** [comment]
Hi, it sounds great, could you provide the potential use case as an example so that I can understand your idea more clearly.

**Comment by oathaha** [comment]
Here is my idea
local_model = rule_obj ['local_model'] # get local model from rule_obj
### other code for experiment

In my opinion, some researchers would like to save local model for later use (like for evaluation). So it will be useful for them if they can obtain local model.

**Comment by MichaelFu1998-create** [comment]
Agree.  Will update the code to implement this.  Thanks!
