### ISSUE TITLE
Global model choice

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#4]
I encounter error when I want to use other global models apart from RandomForest.

I think the cause of error is the following code
![image](https://user-images.githubusercontent.com/29193812/114310238-61f48c80-9b14-11eb-9f26-cb9278e35f39.png)

So I think it would be good if we can use any classification model that is based on sklearn.

**Comment by MichaelFu1998-create** [comment]
Yes, your guess is correct.  Previously Kla said we only supported RF model.  I can change the validation to all sklearn classification.  Could you please confirm with Kla as well.  Thank you!

**Comment by MichaelFu1998-create** [comment]
updated
