### ISSUE TITLE
Cannot import pyexplainer

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#6]
After I install pyexplainer by this command
`pip install pyexplainer`

I cannot import pyexplainer because of this error:
"ModuleNotFoundError: No module named 'pyexplainer'"

Could you help me fix this issue? I have to create replication package.

**Comment by MichaelFu1998-create** [comment]
Did you use the same or similar environment to the #1?
May I have a complete screenshot of your error message?
Thanks!

**Comment by oathaha** [comment]
Actually after I create conda environemnt and run `pip install pyexplainer`, I forgot to use this conda environment in Jupyter notebook so I encountered this error.
