### ISSUE TITLE
import RuleFit error

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#7]
I found that the below code from 'pyexplainer_pyexplainer.py' that import RuleFit triggers an import error
`from pyexplainer.rulefit import RuleFit`

Here is the error message
![image](https://user-images.githubusercontent.com/29193812/114988870-0550f300-9ec1-11eb-98b6-ba94958deac3.png)

I found that using this code can solve the problem
`from rulefit import RuleFit`

**I found this error because I want to import pyexplainer_pyexplainer.py directly from _pyexplainer_ directory, to ensure that I use the latest code for my experiment.**

So my request is changing `from pyexplainer.rulefit import RuleFit` to `from rulefit import RuleFit` in master branch.

**Comment by MichaelFu1998-create** [comment]
this will not pass the pytest, let me do something else to fix this.

**Comment by oathaha** [comment]
I think if you want to use the original code to import RuleFit, you should update python package in pypi so I can use the latest version of pyExplainer via `pip install ...`

**Comment by MichaelFu1998-create** [comment]
The correct approach should be `from .rulefit import RuleFit`
I've released a new version on PyPI which is 0.1.10
Thanks for pointing out this!
