### ISSUE TITLE
bullet point missing

### ISSUE THREAD

**Issue by oathaha** [awsm-research/pyExplainer#8]
I used PyExplainer to visualize guidance of a defective commit in my dataset. The result is shown below
![image](https://user-images.githubusercontent.com/29193812/115138212-103c8c80-a055-11eb-9847-fabb4863be16.png)

We can see that the bullet point that is shown in readme is missing. I have no idea how to show the bullet point link in the example of readme.

Can you help me to find the solution of this issue?

**Comment by MichaelFu1998-create** [comment]
Sorry I didn't get you. What do you mean by bullet point

**Comment by oathaha** [comment]
I am sorry for not being cleared, I mean I don't see the result similar to this figure
![image](https://user-images.githubusercontent.com/29193812/115138415-2c8cf900-a056-11eb-9fec-7ec7f1500a74.png)

You can see that the stuff in blue oval is missing.
